export const COUNTRY_SCORES: Record<string, number> = {
  USA: 15,
  "United States": 15,
  Canada: 15,
  Australia: 15,
  Germany: 15,
  Denmark: 15,
  Netherlands: 15,
  Sweden: 15,
  Portugal: 13,
  Italy: 13,
  Spain: 13,
  Japan: 13,
  "South Korea": 13,
  Turkey: 11,
  Mexico: 11,
  Brazil: 11,
  China: 9,
  India: 7,
  "Sri Lanka": 7,
  Vietnam: 6,
  Indonesia: 6,
  Thailand: 6,
  Bangladesh: 4,
  Pakistan: 4,
  Cambodia: 4,
  Myanmar: 2,
  Ethiopia: 2,
  Eritrea: 2,
  "North Korea": 0,
  Unknown: 3,
};

export const COUNTRY_NOTES: Record<string, string> = {
  Bangladesh:
    "Very low wages ($95–$170/mo), high compliance risk, frequent labor violations reported",
  China: "Large variance; compliance depends heavily on factory audit certification",
  Myanmar: "Documented forced labor concerns / authoritarian oversight",
  "North Korea": "State-mandated forced labor documented by UN",
  USA: "Strong labor law enforcement, min wage ≥ living wage",
  Germany: "Strong protections, garment industry well-regulated",
};
