export const FIBER_SCORES: Record<string, number> = {
  organic_cotton_gots: 25,
  hemp: 24,
  linen: 23,
  lyocell_tencel: 22,
  recycled_wool: 21,
  wool_mulesing_free: 19,
  organic_cotton: 18,
  modal_ecovero: 17,
  cotton: 14,
  recycled_polyester: 13,
  recycled_nylon: 13,
  bamboo: 12,
  viscose: 10,
  rayon: 10,
  wool: 9,
  nylon: 5,
  polyester: 4,
  acrylic: 2,
  spandex: 3,
  elastane: 3,
  lycra: 3,
};

export const FIBER_WATER_SCORES: Record<string, number> = {
  hemp: 7,
  linen: 7,
  organic_cotton_gots: 6,
  organic_cotton: 6,
  lyocell_tencel: 6,
  modal_ecovero: 5,
  recycled_wool: 5,
  wool_mulesing_free: 4,
  wool: 4,
  recycled_polyester: 4,
  recycled_nylon: 4,
  bamboo: 4,
  cotton: 3,
  polyester: 4,
  nylon: 4,
  acrylic: 3,
  viscose: 3,
  rayon: 3,
  spandex: 3,
  elastane: 3,
};

export const SYNTHETIC_FIBERS = new Set([
  "polyester",
  "nylon",
  "acrylic",
  "spandex",
  "elastane",
  "lycra",
  "recycled_polyester",
  "recycled_nylon",
]);

export const FIBER_LABELS: Record<string, string> = {
  organic_cotton_gots: "GOTS Organic Cotton",
  hemp: "Hemp",
  linen: "Linen / Flax",
  lyocell_tencel: "TENCEL™ Lyocell",
  recycled_wool: "Recycled Wool",
  wool_mulesing_free: "Mulesing-Free Wool",
  organic_cotton: "Organic Cotton",
  modal_ecovero: "ECOVERO™ Modal",
  cotton: "Conventional Cotton",
  recycled_polyester: "Recycled Polyester (rPET)",
  recycled_nylon: "Recycled Nylon",
  bamboo: "Bamboo",
  viscose: "Viscose / Rayon",
  rayon: "Rayon",
  wool: "Conventional Wool",
  nylon: "Nylon",
  polyester: "Virgin Polyester",
  acrylic: "Acrylic",
  spandex: "Spandex",
  elastane: "Elastane",
  lycra: "Lycra",
};
